### PR TITLE
Fixed wmediumd integration

### PR DESCRIPTION
**Pull request by patgrosse**
* wmediumd is always started in a tmux session
* tmux is installed with wmediumd
* wmediumd service can be started before Mininet-Wifi Stations can do network activity

### Dynamic:
wmediumd is started after the network is started.

Pro: MAC addresses can be automatically retrieved
Con: tools like `iw station dump` obviously use some kind of cache

Example: `wmediumd_ibss_dynamic.py`

### Static:
wmediumd is started before the network is started.

Pro: Packets can be captured from the beginning
Con: MAC addresses have to be entered manually

Example: `wmediumd_ibss_static.py`

### CODE REVIEW

**Comment by ramonfontes** [comment]
It's mandatory the using of tmux in wmediumd_ibss_static.py? Can we swift its position to after adding the stations? I'm thinking in a better way to get the interface and mac address by using attributes.

**Comment by patgrosse** [comment]
I had problems setting the MAC addresses for interfaces in adhoc mode. I think they are completly ignored, because I couldn't find the `hw ether` command in the debug output. If I start the `wifiPosition.py` example with debug logging, I can see the MAC address being assigned through the `hw ether` command. That is the reason, I created the "full" static example.

**Comment by ramonfontes** [comment]
Ok. Let's see now after new changes? Please note that I just changed net.py
and wifiModule.py. In net.py there is a function
called configureWifiNodes() and in that function I
call module.assignIface(), that is responsible for assigning interfaces for
all Nodes. After module.assignIface() you can call a new method to do the
work of StaticWmediumdIntfRef. You can capture the MAC address and
interface through staX.params['mac'] and staX.params['wlan'].

2016-11-21 16:19 GMT-02:00 Patrick Große <notifications@github.com>:

**Comment by patgrosse** [comment]
I added another example using "dynamic MAC resolution" but intercepting Mininet on startup. If these are too much examples for this specific case, I can delete `wmediumd_ibss_static.py` and `wmediumd_ibss_dynamic.py` if you want to.

**Pull request merged**
