### PR TITLE
Add CONFIG_DPP to the config.patch.  

### PR DESCRIPTION
**Pull request by ranganathanm**
Add wireshark startup to the eap-tls example,

### CODE REVIEW

**Comment by ramonfontes** [comment]
What do you think about keeping the current version of hostap and only add CONFIG_DPP at the end of the patch? Some flags seems to be removed through your commit.

**Comment by ranganathanm** [comment]
Sure. Sorry I guess I made a mistake.

Thanks,

Ranga
________________________________

**Comment by ramonfontes** [comment]
It seems that the current _config.patch_ already includes CONFIG_DPP [#L158](https://github.com/intrig-unicamp/mininet-wifi/blob/master/util/hostap-patches/config.patch#L158)

**Comment by ranganathanm** [comment]
Thanks and sorry for the confusion.
________________________________

**Pull request closed without merging**
