### PR TITLE
Adjust (number of packets and throuput) extractions from car and core switch

### PR DESCRIPTION
**Pull request by JafarbadarnehAG**
fix data extraction from ifconfig version with different kernel versions 4.4.0-59-generic and 4.6 under Ubuntu 16.04 LTS

### CODE REVIEW

**Comment by SUFEIYA** [comment]
hi
i want help for impelementation this project
when i run this I see this error
*** Generating graphic
Traceback (most recent call last):
  File "vanet.py", line 346, in <module>
    topology()
  File "vanet.py", line 332, in topology
    graphic()
  File "vanet.py", line 61, in graphic
    l1.append(int(p[0]))
ValueError: invalid literal for int() with base 10: 'errors:0'

**Comment by ramonfontes** [comment]
Hi,

Please be sure you're able to get RX packets by means of this line
<https://github.com/ramonfontes/reproducible-research/blob/master/mininet-wifi/IEEE-Access-2017/vanet.py#L262>.
It might be different in some kernel versions.

2017-09-19 10:41 GMT-03:00 SUFEIYA <notifications@github.com>:

**Comment by SUFEIYA** [comment]
Hi,
Can it run on Ubuntu  ? Or it must run on others

**Comment by ramonfontes** [comment]
Ubuntu.

**Comment by SUFEIYA** [comment]
Hello,
 I change the kernel tov4.7 .But I still have this error
Traceback (most recent call last):
  File "vanet.py", line 345, in <module>
    topology()
  File "vanet.py", line 149, in topology
    net.addLink(rsu1, car[0])
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post4-py2.7.egg/mininet/net.py", line 679, in addLink
    cls.associate(sta, ap, self.useWmediumd, mininetWiFi.enable_interference)
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post4-py2.7.egg/mininet/wifiLink.py", line 350, in associate
    self.configureWirelessLink(sta, ap, wlan, useWmediumd, enable_interference)
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post4-py2.7.egg/mininet/wifiLink.py", line 310, in configureWirelessLink
    self.updateParams(sta, ap, wlan)
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post4-py2.7.egg/mininet/wifiLink.py", line 341, in updateParams
    sta.params['mode'][wlan] = ap.params['mode'][0]
IndexError: list assignment index out of range
what should I do ?
Thank you for help!

**Comment by ramonfontes** [comment]
Why did you install a new kernel?? Why didn't you adjust the code in order to get RX Packets? I really don't know what you're doing there. Did you run it in debug level? The information you provided doesn't help me to indetify the problem.

**Comment by ramonfontes** [comment]
I just updated [vanet.py](https://github.com/ramonfontes/reproducible-research/commit/d00d279a0eb0a675ed61598bcd78706bfb58f2e9) and the branch [dev1](https://github.com/intrig-unicamp/mininet-wifi/commit/b07a5faa037d3e55c40d71e4c17c50b3acfa9603).

**Comment by SUFEIYA** [comment]
Hi
I am sorry , I have encountered a problem can't be solved again.
I modified the vanet.py, when I run I see this error
Traceback (most recent call last):
  File "vanet.py", line 345, in <module>
    topology()
  File "vanet.py", line 128, in topology
    car[x] = net.addcar('car%s' % (x), ip='10.0.0.%s/8' % (x + 1), \
AttributeError: 'Mininet' object has no attribute 'addcar'
And I also modified the vanet.py.
I am a new one.
Thanks for help again!

**Comment by ramonfontes** [comment]
addcar or addCar?

**Comment by SUFEIYA** [comment]
addCar

**Comment by ramonfontes** [comment]
File "vanet.py", line 128, in topology
car[x] = net.addcar('car%s' % (x), ip='10.0.0.%s/8' % (x + 1), 
AttributeError: 'Mininet' object has no attribute 'addcar'

**Comment by SUFEIYA** [comment]
Hi,
The code is 
for x in range(0, 4):
        car[x] = net.addCar('car%s' % (x), ip='10.0.0.%s/8' % (x + 1), 
'addCar'  not 'addcar'

**Comment by ramonfontes** [comment]
Why the message says addcar??

**Comment by SUFEIYA** [comment]
Hi,
How do I update your updated code about mininet ?
In addition to line by line to update.

**Comment by ramonfontes** [comment]
Pull request applied in https://github.com/ramonfontes/reproducible-research/blob/master/mininet-wifi/IEEE-Access-2017/vanet.py.

**Comment by SUFEIYA** [comment]
I am not saying  the vanet.py but said the node.py or net.py......

**Comment by ramonfontes** [comment]
This pull request is about vanet.py. Moreover, the msg you sent here says:

File "vanet.py", line 128, in topology
car[x] = net.addcar('car%s' % (x), ip='10.0.0.%s/8' % (x + 1), 
AttributeError: 'Mininet' object has no attribute 'addcar'

How addcar (not addCar) has appeared???

**Comment by SUFEIYA** [comment]
Now, the error is 
*** Creating nodes
*** Configuring wifi nodes
*** Creating links
Traceback (most recent call last):
  File "vanet.py", line 345, in <module>
    topology()
  File "vanet.py", line 149, in topology
    net.addLink(rsu1, car[0])
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post4-py2.7.egg/mininet/net.py", line 676, in addLink
    if dist > ap.params['range']:
KeyError: 'range'
Not the AttributeError: 'Mininet' object has no attribute 'addcar'
I think  it is sloved by updating the code of the mininet-wifi
I'am right?

**Comment by SUFEIYA** [comment]
Hi,
Now I can run the project, and the result is 

It's wrong, how can I solve it?

**Comment by ramonfontes** [comment]
Is cvlc working? What about the commands responsible for getting the
results from interface? Did you check them?

**Comment by SUFEIYA** [comment]
Sorry,
How do i know if cvlc is working?
I installed vlc

**Comment by SUFEIYA** [comment]
Hello,
I know my problem, the vlc  dindn't  work
[0x7f1004000ec8] live555 demux error: Failed to connect with rtsp://:8554/helmet.sdp
[0x7f100c0009b8] main input error: open of `rtsp://:8554/helmet.sdp' failed

**Comment by SUFEIYA** [comment]
Excuse,
I still don't solve my problem, I want to know before you run the code what did you do for vlc ?
And how to configure vlc?
Thankyou  for help!

**Comment by ramonfontes** [comment]
Did you run the vlc command on your host? If vlc isn't working, in my
opinion, you should reproduce the same command on your host.

**Comment by SUFEIYA** [comment]
Hello,
How to configure the ip of client and switch ?
In the code, the client ip  is 200.0.10.100, the ip is for Brazil. Should I put  it into local ?
Thanks!

**Comment by SUFEIYA** [comment]
Hello,
What the mean of stas ?
` for idx in range(0, cars):
        car.append(idx)
        stas.append(idx)`
`for v in net.carsSTA:
        v.cmd('ifconfig %s-eth0 192.168.1.%s/24 up' % (v, j))`
Thanks!

**Comment by SUFEIYA** [comment]
Hello,
My result is 
image
I tested the connectivity, and found
mininet-wifi>  pingpair
client -> *** client : ('ping -c1  192.168.1.1',)
connect: Network is unreachable
X 
car0 -> *** car0 : ('ping -c1  200.0.10.2',)
PING 200.0.10.2 (200.0.10.2) 56(84) bytes of data.
From 200.0.10.100 icmp_seq=1 Destination Host Unreachable


--- 200.0.10.2 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

X 
*** Results: 100% dropped (0/2 received)

**Comment by SUFEIYA** [comment]
Excuse,
The problem is when the car moving, the vlc of client is closed.
How to solve it ?
Thank you for help!

**Comment by SUFEIYA** [comment]
Hello,
I have solved my problems, and I have disturbed you for more time.
Thank you so much !!!

**Comment by SUFEIYA** [comment]
Hello,
I reinstalled the mininet-wifi three days ago, the code about the vanet.py couldn't run.
*** Creating nodes
***Configuring Propagation Model
*** Configuring wifi nodes
Traceback (most recent call last):
  File "vanet2.py", line 371, in <module>
    topology()
  File "vanet2.py", line 157, in topology
    net.configureWifiNodes()  
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post5-py2.7.egg/mininet/net.py", line 771, in configureWifiNodes
    self.stations, self.accessPoints = mininetWiFi.configureWifiNodes(**params)
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post5-py2.7.egg/mininet/wifiNet.py", line 1000, in configureWifiNodes
    self.configureWirelessLink(stations, accessPoints, cars)
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post5-py2.7.egg/mininet/wifiNet.py", line 825, in configureWirelessLink
    self.configureMacAddr(node)
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post5-py2.7.egg/mininet/wifiNet.py", line 972, in configureMacAddr
    if node.params['mac'][wlan] == '':
IndexError: list index out of range
I also ran the vanet.py in the mininet-wifi/examples . The code couldn't be ran either.

**Pull request closed without merging**
