### PR TITLE
Fixed the example and added some notes in README

### PR DESCRIPTION
**Pull request by ranganathanm**

### CODE REVIEW

**Comment by ramonfontes** [comment]
`os.path.realpath` will work perfectly after applying https://github.com/intrig-unicamp/mininet-wifi/commit/f5336a81761cf7e51f5f859aba3805594db481d3. Hence, you can replace `os.getcwd()` with it. You can take [#L32](https://github.com/intrig-unicamp/mininet-wifi/blob/master/mn_wifi/telemetry.py#L32) as reference. The advantage of this approach it that you can run the code from any directory.

**Comment by ramonfontes** [comment]
It seems that you've updated the hostap submodule and this is causing error in Travis.

_Submodule hostap updated from 12de14 to 9ea227_

**Comment by ranganathanm** [comment]
Oh. I wanted to update my fork but instead it appears I updated master!

I needed to apply a fix for hostap to get the dpp example to work. Can you reject my submodule update. I can submit it as a diff.

Ranga

**Comment by ranganathanm** [comment]
When I push to my fork, why does travis pick it up?



From: Ranganathan, Mudumbai (Fed)
Sent: Sunday, October 20, 2019 4:31 PM
To: intrig-unicamp/mininet-wifi <reply@reply.github.com>; intrig-unicamp/mininet-wifi <mininet-wifi@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [intrig-unicamp/mininet-wifi] Fixed the example and added some notes in README (#256)

Oh. I wanted to update my fork but instead it appears I updated master!

I needed to apply a fix for hostap to get the dpp example to work. Can you reject my submodule update. I can submit it as a diff.

Ranga

**Comment by ramonfontes** [comment]
Your PR is still open. If you change your code, the PR will automatically be changed as well.

**Comment by ranganathanm** [comment]
I forked mininet wifi and upgraded hostapd to the latest version (I was having some issues). When I committed and pushed to my fork, for some reason travis picked it up and complained about my commit/push.
1. Why is this happening? i.e. why is travis complaining about my fork? I was hoping to submit a PR. Does travis build all forks of mininet-wifi?
2. Why is there a freeze on hostapd? Rather brittle IMHO. Hostapd is evolving and going through numerous bug fixes all the time. Freezing to a version means you can't update to the latest version.

**Comment by ramonfontes** [comment]
1. As I said, your PR was open. This means that all the changes will be applied in your PR. Travis builds the PR automatically. You change your code, PR changes, and travis does a new test.
2. I wouldn't say freeze. Hostapd has been added as a submodule. We cannot simply apply a single diff file for all the hostapd versions. It won't work. On the other hand, if you want to update the submodule with the current CONFIGs, you can do so.

**Pull request closed without merging**
