### PR TITLE
Completely separate Mininet-wifi and Mininet code

### PR DESCRIPTION
**Pull request by zephyrmoth**
The current system of distributing an alternate version of the "mininet" module within Mininet-wifi not only causes issues with managing installs of both programs on the system or using code from both Mininet and Mininet-wifi in derivative software (for example, the lack of parity between their respective versions of examples/cluster.py), but also entails an ongoing maintenance burden to maintain parity with Mininet itself.
This patch removes all Mininet code currently distributed within Mininet-Wifi and restructures the project such that Mininet is treated as a dependency, which should serve to alleviate the above problems.

### CODE REVIEW

**Comment by ramonfontes** [comment]
/mininet/node.py doesn't include [plot()](https://github.com/intrig-unicamp/mininet-wifi/blob/master/mininet/node.py#L642). This is the only method added in mininet in order to plot nodes provided by mininet.

**Comment by ramonfontes** [comment]
Yes. Maybe the second one.

**Comment by ramonfontes** [comment]
@zephyrmoth I was thinking.. `plot()` will cause too many "_undesirable_" changes in the code. So, let's keep the mininet code as it is and then I'll think better about it. I confess that I am thinking of using _monkeypatch_ instead.

**Comment by zephyrmoth** [comment]
To confirm, you would prefer I roll back 1fa75eb, or not move forward with the changes altogther?

**Comment by ramonfontes** [comment]
Only roll back [1fa75eb](https://github.com/intrig-unicamp/mininet-wifi/commit/1fa75eb5905ed69f380c8a068d1c1a5d63abf02f).

**Comment by ramonfontes** [comment]
Could you resolve the latest conflicts? I will merge the code after that.

**Comment by zephyrmoth** [comment]
I'll get on it promptly.

**Pull request merged**
